Rounded corners for docked mode
sindresorhus/touch-bar-simulator pull request #54
Opened 2019-09-09 13:19 UTC by DeveloperBen

Fixes #34 
Set cornerRadius to 5.0.

2019-09-09 13:39 UTC, sindresorhus commented
> but since the docked mode is not using a window frame, we will have to implement the rounded corners for the **bottom left/right** manually.

2019-09-09 14:21 UTC, DeveloperBen commented
![image](https://user-images.githubusercontent.com/17319613/64538945-dd310380-d31d-11e9-8e85-5754c407a6b5.png)

2019-09-09 15:12 UTC, sindresorhus commented
It should only be round on the edge that is not touching the screen edge. In your screenshot, it should only have rounded top-left and top-right corners.

2019-09-09 17:25 UTC, DeveloperBen commented
Oh, ok I will try to do that

2019-09-09 17:43 UTC, GoldenChaos commented
(To inject some subjective opinion/feature creep, it would be great to eventually be able to specify a distance from the edge of the screen and have all 4 corners be rounded if this is true!)

2019-09-09 18:10 UTC, DeveloperBen commented
@sindresorhus I updated it
![image](https://user-images.githubusercontent.com/17319613/64555523-d0240c80-d33d-11e9-9290-cc9ef0c811fd.png)
![image](https://user-images.githubusercontent.com/17319613/64555535-d7e3b100-d33d-11e9-8a70-d1e50862a659.png)

2019-09-13 09:10 UTC, sindresorhus commented
If I set "Dock to Bottom", then restart the app, and then select "Dock to Top", there's some kind of visual glitch:

<img width="511" alt="Screenshot 2019-09-13 at 14 17 09" src="https://user-images.githubusercontent.com/170270/64851105-efbe7c00-d640-11e9-8095-92e20b27dbcc.png">

2019-09-13 09:15 UTC, sindresorhus requested changes

2019-09-13 09:15 UTC, sindresorhus commented on Touch Bar Simulator/TouchBarWindow.swift
> +		self.contentView?.layer?.borderWidth = 0.0
This logic could be moved out into a `CALayer` extension to be reusable.

Could also add a `NSWindow` extension that used this and also handled `isOpaque`, etc.

2019-09-13 09:15 UTC, sindresorhus commented on Touch Bar Simulator/TouchBarWindow.swift
> +		self.contentView?.layer?.borderColor = .clear
I don't think this is needed as you already set the `borderWidth`.

2019-09-13 09:15 UTC, sindresorhus commented on Touch Bar Simulator/TouchBarWindow.swift
> +		self.contentView?.layer?.maskedCorners = []
This is already set below.

2019-09-13 09:15 UTC, sindresorhus commented on Touch Bar Simulator/TouchBarWindow.swift
> +		self.contentView?.layer?.cornerRadius = 7.5
Maybe add a comment that the 7.5 number is to match the window corner radius.

2019-09-13 09:15 UTC, sindresorhus commented on Touch Bar Simulator/TouchBarWindow.swift
> +		self.backgroundColor = .clear
Shouldn't this be set to the opposite here https://github.com/sindresorhus/touch-bar-simulator/pull/54/files#diff-e6aaf782da40568071255e5e366b109dR284?

2019-09-13 09:15 UTC, sindresorhus commented on Touch Bar Simulator/TouchBarWindow.swift
> +				window.roundCorners([.layerMaxXMinYCorner, .layerMinXMinYCorner])
Add a couple of `CACornerMask` extensions to make this and the below call nicer. `.minY` and `.maxY`.

2019-10-25 05:54 UTC, sindresorhus commented
@DeveloperBen Friendly bump :)

2019-11-24 10:08 UTC, sindresorhus commented
This also needs to use corner radius on all 4 sides when docked with a padding: https://github.com/sindresorhus/touch-bar-simulator/pull/63

2020-02-16 17:37 UTC, closed without merging

2023-12-17 03:37 UTC, ThinkFar commented
Any update on this? What's missing? Why is this not merged?